/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author minht
 */
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import View.ClassTableModel;
import Model.*;
import java.sql.*;
import Dao.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
public class ViewPhim_NV extends javax.swing.JFrame {

    /**
     * Creates new form ViewPhim
     */
    List<Phim> listItem;
    List<PhimThem> listpt;
    TableRowSorter<TableModel> rowSorter = null;
    Connection cons = null;
    SimpleDateFormat sdf;
    SimpleDateFormat sdfd;
    DefaultTableModel dtm;
    public ViewPhim_NV() {
        initComponents();
        sdf = new SimpleDateFormat("yyyy/MM/dd");
        sdfd = new SimpleDateFormat("yyyy-MM-dd");
//        ImageIcon imgi = new ImageIcon("C:\\Users\\minht\\Documents\\NetBeansProjects\\doan_QLRP\\src\\resources\\home.png");
//        Image img = imgi.getImage();
//        Image newimg = img.getScaledInstance(home.getWidth(), home.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imgi = new ImageIcon(newimg);
//        home.setIcon(imgi);
//        imgi = new ImageIcon("C:\\Users\\minht\\Documents\\NetBeansProjects\\doan_QLRP\\src\\resources\\locate.png");
//        img = imgi.getImage();
//        newimg = img.getScaledInstance(jLabel14.getHeight(), jLabel14.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imgi = new ImageIcon(newimg);
//        jLabel14.setIcon(imgi);
//        
//        home.addMouseListener(new MouseListener(){
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                JOptionPane.showMessageDialog(rootPane, "chua code");
//            }
//
//            @Override
//            public void mousePressed(MouseEvent e) {
//                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//            }
//
//            @Override
//            public void mouseReleased(MouseEvent e) {
//                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//            }
//
//            @Override
//            public void mouseEntered(MouseEvent e) {
//                jPanel4.setBackground(new Color(250,250,250));
//            }
//
//            @Override
//            public void mouseExited(MouseEvent e) {
//                jPanel4.setBackground(new Color(127,127,127));
//            }
//            
//        });
        cons = DBConnect.getConnectionMySql("root", "");
        if(cons == null){
            JOptionPane.showMessageDialog(rootPane, "khong the ket noi co so du lieu");
            return;
        }
        listItem = PhimDAO.getAll(cons);
        listpt = PhimThemDAO.getAll(cons);
        String[] str = {"ma phim", "ten phim" , "loai phim", "tac gia", "quoc gia", "thoi luong", "nam phat hanh"};
        dtm = ClassTableModel.setTablePhim(listItem, str);
        rowSorter = new TableRowSorter<>(dtm);
        tbl.setModel(dtm);
        tbl.setRowSorter(rowSorter);
        search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = search.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = search.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tenp = new javax.swing.JTextField();
        map = new javax.swing.JTextField();
        quocg = new javax.swing.JTextField();
        thoil = new javax.swing.JTextField();
        Dongy = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Them = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        thel = new javax.swing.JTextField();
        daod = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mota = new javax.swing.JTextArea();
        namsx = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jPanel2.setBackground(new java.awt.Color(157, 157, 157));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(622, 45));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Phim");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(622, 45));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Linh Trung, Thu Duc, TPHCM");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Rap Chieu Phim");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(607, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel5.setBackground(new java.awt.Color(220, 205, 205));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setPreferredSize(new java.awt.Dimension(622, 45));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ten phim");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mã phim");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("The Loai");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tac gia");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Mo ta");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Thoi luong");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nam san xuat");

        Dongy.setText("Dong y");
        Dongy.setMaximumSize(new java.awt.Dimension(72, 35));
        Dongy.setMinimumSize(new java.awt.Dimension(72, 35));
        Dongy.setPreferredSize(new java.awt.Dimension(75, 35));
        Dongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DongyActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.setPreferredSize(new java.awt.Dimension(75, 35));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Them.setText("Them");
        Them.setPreferredSize(new java.awt.Dimension(75, 35));
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Xoa.setText("Xoa");
        Xoa.setPreferredSize(new java.awt.Dimension(75, 35));
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Quoc gia");

        mota.setColumns(20);
        mota.setRows(5);
        jScrollPane2.setViewportView(mota);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Them, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dongy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(map, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(thel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(49, 49, 49))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(121, 121, 121))
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(99, 99, 99))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(quocg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thoil, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(tenp)
                            .addComponent(daod)
                            .addComponent(namsx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Reset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Xoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 18, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(thel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quocg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(daod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thoil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dongy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel6.setBackground(new java.awt.Color(121, 82, 144));
        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);
        jPanel6.setPreferredSize(new java.awt.Dimension(622, 45));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        search.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        PhimThem pt = null;
        System.out.println(tbl.getSelectedRow());
        Phim p = listItem.get(tbl.getSelectedRow());
        for(PhimThem i : listpt){
            if(i.getMa_phim() == p.getMa_phim()){
                pt = i;
                break;
            }
        }
        map.setText(String.valueOf(p.getMa_phim()));
        tenp.setText(p.getTen_phim());
        quocg.setText(p.getQuoc_gia());
        thoil.setText(String.valueOf(p.getThoi_luong()));
        try{
            namsx.setDate(sdfd.parse(p.getNam_phat_hanh()));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "nam san xuat sai format");
        }
        thel.setText(p.getLoai_phim());
        daod.setText(p.getTac_gia());
        if(pt == null) return;
        mota.setText(pt.getMo_ta());
    }//GEN-LAST:event_tblMouseClicked

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        map.setText("");
        tenp.setText("");
        quocg.setText("");
        thoil.setText("");
        namsx.cleanup();
        namsx.setDate(Date.valueOf(LocalDate.now()));
        mota.setText("");
        daod.setText("");
        thel.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        if(map.getText().equals("") == true) return;
        int i = PhimThemDAO.delete(cons, listpt.get(tbl.getSelectedRow()));
        if(i == -1){
            JOptionPane.showMessageDialog(rootPane, "loi co so du lieu");
        }
        else if( i == 0){
            JOptionPane.showMessageDialog(rootPane, "khong tim duoc phim");
        }
        else{
            listpt.remove(tbl.getSelectedRow());
            int j = PhimDAO.delete(cons, listItem.get(tbl.getSelectedRow()));
            if(j == -1){
                JOptionPane.showMessageDialog(rootPane, "loi co so du lieu");
            }
            else if (i == 0){
                JOptionPane.showMessageDialog(rootPane, "khong tim duoc phim");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "da xoa thanh cong");
                listItem.remove(tbl.getSelectedRow());
                dtm.removeRow(tbl.getSelectedRow()); 
                map.setText("");
                tenp.setText("");
                quocg.setText("");
                thoil.setText("");
                namsx.cleanup();
                namsx.setDate(Date.valueOf(LocalDate.now()));
                mota.setText("");
                daod.setText("");
                thel.setText("");
            }
                 
            
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        if(tenp.getText().equals("") == true) return;
        if(quocg.getText().equals("") == true) return;
        if(thoil.getText().equals("") == true) return;
        if(namsx.getDate() == null) return;
        if(daod.getText().equals("")) return;
        if(mota.getText().equals("")) return;
        if(thel.getText().equals("")) return;
        try{ 
            int i = Integer.parseInt(thoil.getText());
            if(i <= 0){
                JOptionPane.showMessageDialog(rootPane, "thoi luong la so nguyen duong");
                return;
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "thoi luong la so nguyen duong");
            return;
        }
        Phim p;
        if(map.getText().equals("") == true){
            p = new Phim(tenp.getText(),thel.getText(), daod.getText(), quocg.getText(), Integer.parseInt(thoil.getText()), sdfd.format(namsx.getDate()));
        }
        else{
            try{ 
                int j = Integer.parseInt(map.getText());
                if(j <= 0){
                    JOptionPane.showMessageDialog(rootPane, "ma phim la so nguyen duong");
                    return;
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "ma phim la so nguyen duong");
                return;
            }
            p = new Phim(Integer.parseInt(map.getText()),tenp.getText(),thel.getText(), daod.getText(), quocg.getText(), Integer.parseInt(thoil.getText()), sdfd.format(namsx.getDate()));
        }
        int i = PhimDAO.insert(cons, p);
        if(i == 0 || i == -1) {
            JOptionPane.showMessageDialog(rootPane, "them phim that bai");
            return;
        }
        Phim phi = PhimDAO.getByTenPhim(cons, tenp.getText());
        if(phi == null){
            JOptionPane.showMessageDialog(rootPane, "them phim that bai. Khong lay duoc phim");
            return;
        }
        PhimThem pt;
        pt = new PhimThem(phi.getMa_phim(), mota.getText(), null);
        int t = PhimThemDAO.insert(cons, pt);
        if(t == -1){
            JOptionPane.showMessageDialog(rootPane, "loi co so du lieu");
        }
        else if( t == 0){
            JOptionPane.showMessageDialog(rootPane, "khong them duoc phim them");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "da them thanh cong");
            //{"ma phim", "ten phim" , "loai phim", "tac gia", "quoc gia", "thoi luong", "nam phat hanh"};
            dtm.addRow(new Object[]{phi.getMa_phim(), phi.getTen_phim(), phi.getLoai_phim(), phi.getTac_gia(), phi.getQuoc_gia(), phi.getThoi_luong(), phi.getNam_phat_hanh()});
            listItem.add(phi);
            listpt.add(pt);
            map.setText(String.valueOf(phi.getMa_phim()));
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void DongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DongyActionPerformed
        if(map.getText().equals("")) return;
        if(namsx.getDate() == null) return;
        if(tenp.getText().equals("") == true) return;
        if(quocg.getText().equals("") == true) return;
        if(thoil.getText().equals("") == true) return;
        if(daod.getText().equals("")) return;
        if(thel.getText().equals("")) return;
        Phim p;
        try{
            p = new Phim(Integer.parseInt(map.getText()),tenp.getText(),thel.getText(), daod.getText(), quocg.getText(), Integer.parseInt(thoil.getText()), sdfd.format(namsx.getDate()));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "ma nhan vien hoac ma tai khoan la so");
            return;
        }
        int t = PhimDAO.update(cons, p);
        if(t == -1){
            JOptionPane.showMessageDialog(rootPane, "loi co so du lieu");
        }
        else if( t == 0){
            JOptionPane.showMessageDialog(rootPane, "khong sua duoc phim");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "da sua thanh cong");
            //{"ma phim", "ten phim" , "loai phim", "tac gia", "quoc gia", "thoi luong", "nam phat hanh"};
            tbl.setValueAt(p.getMa_phim(), tbl.getSelectedRow(), 0);
            tbl.setValueAt(p.getTen_phim(), tbl.getSelectedRow(), 1);
            tbl.setValueAt(p.getLoai_phim(), tbl.getSelectedRow(), 2);
            tbl.setValueAt(p.getTac_gia(), tbl.getSelectedRow(), 3);
            tbl.setValueAt(p.getQuoc_gia(), tbl.getSelectedRow(), 4);
            tbl.setValueAt(p.getThoi_luong(), tbl.getSelectedRow(), 5);
            tbl.setValueAt(p.getNam_phat_hanh(), tbl.getSelectedRow(), 6);
        }
        
        PhimThem pt;
        try{
            pt = new PhimThem(Integer.parseInt(map.getText()),mota.getText(),null);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "loi cap nhat phim them la so");
            return;
        }
        int i = PhimThemDAO.update(cons, pt);
        if(i == 0 || i == -1) {
            JOptionPane.showMessageDialog(rootPane, "cap nhat phim them that bai");
            return;
        }
        else if(i == 1) JOptionPane.showMessageDialog(rootPane, "Sua phim them thanh cong");
    }//GEN-LAST:event_DongyActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TrangChu_NV().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dongy;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.JTextField daod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField map;
    private javax.swing.JTextArea mota;
    private com.toedter.calendar.JDateChooser namsx;
    private javax.swing.JTextField quocg;
    private javax.swing.JTextField search;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tenp;
    private javax.swing.JTextField thel;
    private javax.swing.JTextField thoil;
    // End of variables declaration//GEN-END:variables
}
